{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "account.serviceAccountName" . }}
  namespace: develop
  labels:
{{ include "account.labels" . | indent 4 }}
{{- end -}}
